server:
  port: 8083
spring:
  application:
    name: config_server
  cloud:
    config:
      label: dev
      server:
        git:
          uri: https://github.com/qinln/spring-cloud/
          searchPaths: config
          username: your username
          password: your password
