server:
  port: 8083
spring:
  application:
    name: config_server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/qinln/spring-cloud-demo/
          searchPaths: config_server/src/main/resources
          username: username
          password: password
